/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"


void
calculadoraprog_1(char *host, int numero_1, int numero_2, char operator)
{
	CLIENT *clnt;
	int  *result;
	// int suma_1_arg1;
	// int suma_1_arg2;
	// int  *result_2;
	// int resta_1_arg1;
	// int resta_1_arg2;
	// int  *result_3;
	// int multiplicacion_1_arg1;
	// int multiplicacion_1_arg2;
	// int  *result_4;
	// int division_1_arg1;
	// int division_1_arg2;


#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORAPROG, CALCULADORAVER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */


	if (operator == '+') {
		result = suma_1(numero_1, numero_2, clnt);
	}
	else if (operator == '-') {
		result = resta_1(numero_1, numero_2, clnt);
	}
	else if (operator == '*') {
		result = multiplicacion_1(numero_1, numero_2, clnt);
	}
	else if (operator == '/') {
		result = division_1(numero_1, numero_2, clnt);
	}

	if (result == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	printf("%i %c %i = %i\n", numero_1, operator, numero_2, *result);

	// if (operator == '+') {
	// 	xdr_free (xdr_suma_1_argument, result);
	// }
	// else if (operator == '-') {
	// 	xdr_free (xdr_resta_1_argument, result);
	// }
	// else if (operator == '*') {
	// 	xdr_free (xdr_multiplicacion_1_argument, result);
	// }
	// else if (operator == '/') {
	// 	xdr_free (xdr_division_1_argument, result);
	// }


#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	int numero_1, numero_2;
	char operator;

	if (argc < 5) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}

	// Se asignan los argumentos a variables
	host = argv[1];
	numero_1 = strtol(argv[2], NULL, 10);
	operator = *argv[3];
	numero_2 = strtol(argv[4], NULL, 10);

	calculadoraprog_1 (host, numero_1, numero_2, operator);

	exit (0);
}
